export const JobOpenings = [
  {
    id: 1,
    title: "Video Editor",
    slug: "video-editor",
    location: "Mumbai, India",
    type: "Full Time, Hybrid",
    experience: "2+ Years",
    workingHours: "8 Hours",
    salary: "To Be Discussed.",
    about:
      "At Disrptve, we don’t just run social media, we create conversations that stick. If you’re obsessed with culture, trends, and building communities that matter, this one’s for you.",
    lookingFor: [
      "Proven experience (2+ years) as a Video Editor, preferably for a digital agency or brand.",
      "Expert proficiency in Adobe Premiere Pro, After Effects, and the full Creative Suite.",
      "A strong understanding of pacing, narrative, and visual storytelling for short-form video (Reels, Shorts).",
      "Ability to work with motion graphics, basic color grading, and sound design.",
      "Obsessed with social media video trends and viral formats.",
    ],
    responsibilities: [
      "Edit and produce high-impact, scroll-stopping video content for all social platforms.",
      "Collaborate with the creative team to bring storyboards and concepts to life.",
      "Animate simple motion graphics and text overlays to enhance videos.",
      "Manage and organize all raw footage and project files.",
      "Export final-cut videos in various formats, optimized for each platform.",
    ],
  },
  {
    id: 2,
    title: "Content Writer",
    slug: "content-writer",
    location: "Mumbai, India",
    type: "Full Time, Hybrid",
    experience: "2–4 Years",
    workingHours: "8 Hours",
    salary: "To Be Discussed.",
    about:
      "At Disrptve, we don’t just run social media, we create conversations that stick. If you’re obsessed with culture, trends, and building communities that matter, this one’s for you.",
    lookingFor: [
      "2–4 years of experience managing social media for brands.",
      "Strong grasp of Instagram, LinkedIn, Twitter/X, and emerging platforms.",
      "Creative mindset with the ability to write engaging, on-trend copy.",
      "Skilled in planning campaigns and building content calendars.",
    ],
    responsibilities: [
      "Own and grow brand voices across social platforms.",
      "Create scroll-stopping content & campaigns.",
      "Track, analyze, and optimize for performance.",
    ],
  },
  {
    id: 3,
    title: "Graphic Designer",
    slug: "graphic-designer",
    location: "Mumbai, India",
    type: "Full Time, Hybrid",
    experience: "2+ Years",
    workingHours: "8 Hours",
    salary: "To Be Discussed.",
    about:
      "At Disrptve, we don’t just run social media, we create conversations that stick. If you’re obsessed with culture, trends, and building communities that matter, this one’s for you.",
    lookingFor: [
      "A strong portfolio (2+ years experience) showcasing digital and social media design for brands.",
      "Expert proficiency in Adobe Illustrator, Photoshop, and Figma.",
      "A keen understanding of typography, layout, color theory, and brand identity.",
      "Ability to create static, carousel, and simple animated (GIF) content for social media.",
      "Obsessed with visual culture, design trends, and brand aesthetics.",
    ],
    responsibilities: [
      "Design visually stunning, on-brand creative for all social platforms (posts, carousels, stories, ads).",
      "Collaborate with the content team to visualize campaign ideas and marketing concepts.",
      "Develop and maintain brand identity guidelines for various clients.",
      "Create mockups and presentations to pitch creative concepts.",
      "Ensure all visual output is high-quality and platform-optimized.",
    ],
  },
];
