export const ProjectsData = [
  {
    id: 1,
    title: "Imagine",
    heroImg: "/public/images/projects/Imagine/heroImg.webp",
    link: "",
    date: "",
    mode: "",
    tag: "",
    desc: "",
    Images: [
      "/images/projects/Imagine/img1.webp",
      "/images/projects/Imagine/img2.webp",
      "/images/projects/Imagine/img3.webp",
      "/images/projects/Imagine/img4.webp",
      "/images/projects/Imagine/img5.webp",
      "/images/projects/Imagine/img6.webp",
    ],
  },
  {
    id: 2,
    title: "Proost",
    heroImg: "/public/images/projects/Proost/heroImg.webp",
    link: "",
    date: "",
    mode: "",
    tag: "",
    desc: "",
    Images: [
      "/images/projects/Proost/img1.webp",
      "/images/projects/Proost/img2.webp",
      "/images/projects/Proost/img3.webp",
      "/images/projects/Proost/img4.webp",
      "/images/projects/Proost/img5.webp",
      "/images/projects/Proost/img6.webp",
    ],
  },
  {
    id: 3,
    title: "SuperYou",
    heroImg: "",
    link: "",
    date: "",
    mode: "",
    tag: "",
    desc: "",
    Images: [
      "/images/projects/Imagine/img1.webp",
      "/images/projects/Imagine/img2.webp",
      "/images/projects/Imagine/img3.webp",
      "/images/projects/Imagine/img4.webp",
      "/images/projects/Imagine/img5.webp",
      "/images/projects/Imagine/img6.webp",
    ],
  },
  {
    id: 4,
    title: "Devgn CinEx",
    heroImg: "",
    link: "",
    date: "",
    mode: "",
    tag: "",
    desc: "",
    Images: [
      "/images/projects/Imagine/img1.webp",
      "/images/projects/Imagine/img2.webp",
      "/images/projects/Imagine/img3.webp",
      "/images/projects/Imagine/img4.webp",
      "/images/projects/Imagine/img5.webp",
      "/images/projects/Imagine/img6.webp",
    ],
  },
  {
    id: 5,
    title: "Guyana",
    heroImg: "",
    link: "",
    date: "",
    mode: "",
    tag: "",
    desc: "",
    Images: [
      "/images/projects/Imagine/img1.webp",
      "/images/projects/Imagine/img2.webp",
      "/images/projects/Imagine/img3.webp",
      "/images/projects/Imagine/img4.webp",
      "/images/projects/Imagine/img5.webp",
      "/images/projects/Imagine/img6.webp",
    ],
  },
  {
    id: 6,
    title: "Prominance",
    heroImg: "",
    link: "",
    date: "",
    mode: "",
    tag: "",
    desc: "",
    Images: [
      "/images/projects/Imagine/img1.webp",
      "/images/projects/Imagine/img2.webp",
      "/images/projects/Imagine/img3.webp",
      "/images/projects/Imagine/img4.webp",
      "/images/projects/Imagine/img5.webp",
      "/images/projects/Imagine/img6.webp",
    ],
  },
  {
    id: 7,
    title: "Flaunt Your Ink",
    heroImg: "",
    link: "",
    date: "",
    mode: "",
    tag: "",
    desc: "",
    Images: [
      "/images/projects/Imagine/img1.webp",
      "/images/projects/Imagine/img2.webp",
      "/images/projects/Imagine/img3.webp",
      "/images/projects/Imagine/img4.webp",
      "/images/projects/Imagine/img5.webp",
      "/images/projects/Imagine/img6.webp",
    ],
  },
  {
    id: 8,
    title: "Punjab Kings",
    heroImg: "",
    link: "",
    date: "",
    mode: "",
    tag: "",
    desc: "",
    Images: [
      "/images/projects/Imagine/img1.webp",
      "/images/projects/Imagine/img2.webp",
      "/images/projects/Imagine/img3.webp",
      "/images/projects/Imagine/img4.webp",
      "/images/projects/Imagine/img5.webp",
      "/images/projects/Imagine/img6.webp",
    ],
  },
  {
    id: 9,
    title: "India Maritime Week",
    heroImg: "",
    link: "",
    date: "",
    mode: "",
    tag: "",
    desc: "",
    Images: [
      "/images/projects/Imagine/img1.webp",
      "/images/projects/Imagine/img2.webp",
      "/images/projects/Imagine/img3.webp",
      "/images/projects/Imagine/img4.webp",
      "/images/projects/Imagine/img5.webp",
      "/images/projects/Imagine/img6.webp",
    ],
  },
];
