export const ProjectsData = [
  {
    id: 8,
    title: "Imagine",
    tagline: "End-to-end brand custodians.",
    coverImg: "/images/projects/Imagine/coverImg.webp",
    heroImg: "/images/projects/Imagine/heroImg.webp",
    logo: "/images/projects/Imagine/logo.png",
    websiteLink: "",
    tags: [
      "Branding",
      "Packaging",
      "Social Media",
      "Performance",
      "ORM",
      "Quick Commerce Management",
      "Retail Management",
    ],
    challenge:
      "For a fast-growing brand in the plant-based meat industry like Imagine, managing every facet of marketing—from brand perception to retail sales—is a monumental task. They needed a single, trusted partner who could act as an extension of their team, ensuring consistency and driving growth across all channels.",
    approach:
      "We operate as Imagine’s end-to-end brand custodians through a deep, integrated partnership. Our role spans brand strategy, packaging design, social media, performance marketing, and online reputation management (ORM). We also oversee their presence on quick commerce platforms and manage retail marketing and activations. This unified approach ensures every touchpoint works in harmony toward one goal — sustained market leadership.",
    industry: "Plant-Based Meat",
    Images: [
      "/images/projects/Imagine/img1.webp",
      "/images/projects/Imagine/img2.webp",
      "/images/projects/Imagine/img3.webp",
      "/images/projects/Imagine/img4.webp",
      "/images/projects/Imagine/img5.webp",
      "/images/projects/Imagine/img6.webp",
    ],
  },
  {
    id: 2,
    title: "Devgn CinEx",
    tagline: "Building a blockbuster brand for a cinematic icon.",
    coverImg: "/images/projects/devgan/coverImg.webp",
    heroImg: "/images/projects/devgan/heroImg.webp",
    logo: "/images/projects/devgan/logo.png",
    websiteLink: "",
    tags: ["Brand Identity", "Naming", "Creative Strategy"],
    challenge:
      "When a superstar like Ajay Devgn enters the highly competitive cinema space, partnering with a large conglomerate (Vishwa Samudra), the brand needs to feel both premium and personal, while also paying homage to both brands. The task was to create a new identity from scratch that could stand alongside industry giants, reflect the founders’ legacies, and promise a world-class movie-going experience.",
    approach:
      "This project began with the most fundamental question: 'What should we call it?' Our team coined the name 'Devgn CinEx,' creating a direct link to its iconic founder. From there, we architected the entire brand universe. This wasn't just a logo; it was a complete visual system—from the color palette and typography to the on-screen animations and in-venue branding. We delivered a comprehensive brand identity that was modern, powerful, and ready for a nationwide rollout.",
    industry: "Entertainment",
    Images: [
      "/images/projects/devgan/img1.webp",
      "/images/projects/devgan/img2.webp",
      "/images/projects/devgan/img3.webp",
      "/images/projects/devgan/img4.webp",
    ],
  },
  {
    id: 5,
    title: "Prominance",
    tagline: "Building credibility and launching a superstar.",
    coverImg: "/images/projects/prominance/coverImg.webp",
    heroImg: "/images/projects/prominance/heroImg.webp",
    logo: "/images/projects/prominance/logo.png",
    websiteLink: "",
    tags: ["Social Media", "Strategy", "Performance Marketing"],
    challenge:
      "As a leader in the building materials industry, Prominance primarily engaged with a B2B audience. The brand aimed to build broader trust and reinforce its market leadership by introducing Shah Rukh Khan as its brand ambassador. The challenge was to manage this high-profile launch while simultaneously establishing a credible and engaging social media presence from scratch.",
    approach:
      "We implemented a two-pronged strategy. First, we developed and continue to execute a comprehensive social media and performance marketing plan focused on building an authentic community and positioning Prominance as a thought leader. Once that foundation was in place, we seamlessly integrated the Shah Rukh Khan launch into the ecosystem—making the partnership feel purposeful and amplifying the brand’s message of quality and reliability.",
    industry: "Construction and Building Materials",
    Images: [
      "/images/projects/prominance/img1.webp",
      "/images/projects/prominance/img2.webp",
      "/images/projects/prominance/img3.webp",
    ],
  },
  {
    id: 9,
    title: "SuperYou",
    tagline: "Making wellness feel good online.",
    coverImg: "/images/projects/superYou/coverImg.webp",
    heroImg: "/images/projects/superYou/heroImg.webp",
    logo: "/images/projects/superYou/logo.png",
    websiteLink: "",
    tags: ["Social Media", "Creative Strategy", "ORM"],
    challenge:
      "The health and nutrition space is crowded with clinical and often intimidating messaging. SuperYou needed a social media presence that felt vibrant, approachable, and as full of life as its products—building a community around positivity and real-world wellness.",
    approach:
      "We work closely with SuperYou’s talented in-house team to craft a social media strategy that defines a distinct, friendly, and authoritative brand voice. Our creative production leverages AI to deliver unique, visually engaging content designed to educate, inspire, and grow their community. Alongside this, our ORM efforts ensure that conversations around the brand stay positive, supportive, and aligned with its uplifting ethos.",
    industry: "Retail and Health & Nutrition",
    Images: [
      "/images/projects/superYou/img1.webp",
      "/images/projects/superYou/img2.webp",
      "/images/projects/superYou/img3.webp",
    ],
  },
  {
    id: 1,
    title: "Guyana National Campaign",
    tagline: "Shaping a national conversation, from the ground up.",
    coverImg: "/images/projects/guyana/coverImg.webp",
    heroImg: "/images/projects/guyana/heroImg.webp",
    websiteLink: "",
    logo: "/images/projects/guyana/logo.png",
    tags: [
      "Political Strategy",
      "Social Media",
      "Campaign Strategy & Execution",
      "PR",
      "OOH Strategy",
      "Digital Infrastructure",
      "Community Management",
    ],
    challenge:
      "Political campaigns are among the most complex and high-stakes communication challenges in the world. We were tasked with executing a comprehensive national campaign in Guyana, requiring a nuanced understanding of the electorate and the ability to manage a multi-channel strategy under immense pressure. The goal was to shape public opinion, mobilize support, and build an undeniable narrative for victory.",
    approach:
      "We established a central command for the campaign's entire communications and data infrastructure. Our team developed the core narrative and messaging, which was then deployed across every vertical and multiple platforms with multiple pages deployed. This included managing a sophisticated digital strategy with content seeding and community management, continuous social listening to track sentiment, and crafting powerful campaign speeches. We extended our reach offline with on-ground activations and OOH strategy, and even managed the crucial exit poll process to provide real-time data. It was a true 360-degree operation, blending digital precision with real-world impact.",
    industry: "Political",
    Images: [
      "/images/projects/guyana/img1.webp",
      "/images/projects/guyana/img2.webp",
      "/images/projects/guyana/img3.webp",
      "/images/projects/guyana/img4.webp",
      "/images/projects/guyana/img5.webp",
      "/images/projects/guyana/img6.webp",
      "/images/projects/guyana/img7.webp",
    ],
  },
  {
    id: 10,
    title: "Flaunt Your Ink",
    tagline: "From brand identity to brand investment.",
    coverImg: "/images/projects/FYI/coverImg.webp",
    heroImg: "/images/projects/FYI/heroImg.webp",
    logo: "/images/projects/FYI/logo.png",
    websiteLink: "",
    tags: [
      "Brand Identity",
      "Packaging",
      "Celebrity Onboarding",
      "Fundraising Strategy",
    ],
    challenge:
      "Launching a new brand in the competitive beauty and personal care industry requires more than a great product—it demands a powerful identity, instant credibility, and the capital to grow. Flaunt Your Ink needed a partner who could build the brand and the business simultaneously.",
    approach:
      "Our partnership was truly foundational. We began by crafting a complete brand identity and packaging system that felt bold, confident, and market-ready. Leveraging our network, we strategically onboarded Suniel Shetty and Aalim Hakim as brand ambassadors, giving the brand instant star power. To accelerate growth, we also guided the team through their first successful fundraising round—shaping their pitch and helping them secure investment to scale.",
    industry: "Beauty and Personal Care",
    Images: ["/images/projects/FYI/img1.webp"],
  },
  {
    id: 4,
    title: "Proost Beer",
    tagline: "A brand that looks as good as it tastes.",
    coverImg: "/images/projects/Proost/coverVid.gif",
    heroImg: "/images/projects/Proost/1_Proost.webp",
    logo: "/images/projects/Proost/logo.png",
    websiteLink: "",
    tags: [
      "Brand Identity",
      "Packaging",
      "GTM Strategy",
      "Communication Matrix",
    ],
    challenge:
      "The craft beer market is saturated with brands all fighting for attention on crowded shelves. Proost needed more than a great product — it needed a bold, memorable identity that instantly communicated its unique character and made people want to pick it up.",
    approach:
      "We created the complete brand experience, starting with a distinctive logo and visual identity that felt both premium and approachable. The design extended to the packaging, turning each can into a piece of art. Beyond design, we developed a comprehensive Go-to-Market strategy and communication matrix, equipping the Proost team with a clear roadmap on what to say, who to say it to, and where to say it.",
    industry: "Alcohol Beverages",
    Images: [
      "/images/projects/Proost/1_Proost.webp",
      "/images/projects/Proost/2_Proost.webp",
      "/images/projects/Proost/3_Proost.webp",
      "/images/projects/Proost/4_Proost.webp",
    ],
  },
  {
    id: 6,
    title: "Punjab Kings",
    tagline: "Turning passive fans into an active movement.",
    coverImg: "/images/projects/punjabKings/coverImg.webp",
    heroImg: "/images/projects/punjabKings/heroImg.webp",
    logo: "/images/projects/punjabKings/logo.png",
    websiteLink: "",
    tags: ["Community Strategy", "Social Media"],
    challenge:
      "Every IPL team has fans, but not every team has a true community. We saw an opportunity to harness the passion of Punjab Kings supporters and create a dedicated space where they could connect, engage, and feel like an integral part of the team’s journey.",
    approach:
      "Rather than focusing solely on official channels, we built the community from the outside in. We strategized and managed the team’s unofficial fan page and squad, creating a thriving digital ecosystem that felt authentic and fan-led. Through user-generated content, spirited discussions, and a genuine sense of belonging, we transformed casual fans into a movement that amplified the team’s presence far beyond traditional marketing.",
    industry: "Sports",
    Images: [
      "/images/projects/punjabKings/img1.webp",
      "/images/projects/punjabKings/img2.webp",
      "/images/projects/punjabKings/img3.webp",
    ],
  },
  {
    id: 7,
    title: "Tata EV - Harrier Launch",
    tagline: "Driving the launch of an electric icon.",
    coverImg: "/images/projects/tata/coverImg.webp",
    heroImg: "/images/projects/tata/heroImg.webp",
    logo: "/images/projects/tata/logo.png",
    websiteLink: "",
    tags: ["Launch Strategy", "Social Media", "Video Production"],
    challenge:
      "The launch of the Tata Harrier EV marked a defining moment for both the brand and the Indian automotive industry. In a highly competitive and fast-evolving electric vehicle market, the campaign needed to spark massive excitement, showcase cutting-edge features, and lead the social media conversation.",
    approach:
      "We partnered closely with Tata’s internal teams to amplify their launch efforts. Our scope included crafting key strategic elements for the digital rollout, optimizing the main launch film for maximum online engagement, and creating a series of dynamic social creatives designed to build anticipation, educate audiences, and drive bookings from day one.",
    industry: "Automotive",
    Images: [
      "/images/projects/tata/img1.webp",
      "/images/projects/tata/img2.webp",
    ],
  },
  {
    id: 3,
    title: "Sarabh Khanijou",
    tagline: "High fashion, imagined with Artificial Intelligence.",
    coverImg: "/images/projects/sarabh/coverImg.webp",
    heroImg: "/images/projects/sarabh/heroImg.webp",
    logo: "/images/projects/sarabh/logo.png",
    websiteLink: "",
    tags: ["AI Photoshoot", "Creative Production", "Design"],
    challenge:
      "For a high-fashion designer, a lookbook or campaign shoot is a critical asset, but it’s also incredibly expensive and logistically complex, involving models, locations, photographers, and stylists. Sarabh Khanijou needed world-class visuals that would capture the essence of his collection without the prohibitive costs and time commitment of a traditional photoshoot.",
    approach:
      "We bypassed the physical limitations entirely. Using cutting-edge generative AI, we produced a stunning, hyper-realistic photoshoot from scratch. By collaborating closely with the designer on mood boards and creative direction, we were able to generate unique, high-fashion imagery that was indistinguishable from a real-world shoot. This innovative approach allowed for limitless creative freedom while delivering the final assets at 1/8th the cost and in a fraction of the time.",
    industry: "Fashion",
    Images: [
    ],
  },
  {
    id: 11,
    title: "Pune United",
    tagline: "Launching a team, not just a logo.",
    coverImg: "/images/projects/puneUnited/coverImg.webp",
    heroImg: "/images/projects/puneUnited/heroImg.webp",
    logo: "/images/projects/puneUnited/logo.png",
    websiteLink: "",
    tags: ["Brand Identity", "Social Media", "Event Coverage"],
    challenge:
      "Launching a new sports franchise in an emerging league like pickleball meant building a brand that fans could rally behind from day one. Without a legacy, history of wins, or star players, the identity itself needed to spark excitement and create a sense of belonging. The challenge was to build the Pune United brand from the ground up and generate an instant fanbase.",
    approach:
      "We started with the fundamentals: a powerful team identity and jersey design that felt both modern and deeply connected to the spirit of Pune. We then managed the team’s social media debut to build anticipation and establish a community hub even before the first match. To capture and amplify the energy of the launch, we provided live event coverage—ensuring fans everywhere felt part of the action. The result: 8.4 million organic impressions in just one month, and a launch that exceeded both client and fan expectations.",
    industry: "Sports",
    Images: [
      "/images/projects/puneUnited/img1.webp",
      "/images/projects/puneUnited/img2.webp",
      "/images/projects/puneUnited/img3.webp",
      "/images/projects/puneUnited/img4.webp",
      "/images/projects/puneUnited/img5.webp",
      "/images/projects/puneUnited/img6.webp",
      "/images/projects/puneUnited/img7.webp",
      "/images/projects/puneUnited/img8.webp",
      "/images/projects/puneUnited/img9.webp",
    ],
  },
  {
    id: 12,
    title: "Meve Jars",
    tagline: "Launching a brand with star power.",
    coverImg: "/images/projects/meve/heroImg.webp",
    heroImg: "/images/projects/meve/heroImg.webp",
    logo: "/images/projects/meve/logo.png",
    websiteLink: "",
    tags: ["Celebrity Onboarding", "Production", "Packaging"],
    challenge:
      "To break through the crowded and competitive health food market, Meve Jars needed a launch that felt significant, trustworthy, and capable of generating immediate buzz. The goal was to position the brand as a premium and credible player from day one.",
    approach:
      "We architected a launch strategy built around celebrity co-ownership to establish instant credibility. Our team strategically onboarded Shamita Shetty as co-founder, instantly elevating the brand’s profile. We then managed the full-scale production and execution of the launch photoshoot, creating a premium suite of visual assets. Finally, we designed the product packaging to ensure the on-shelf experience matched the brand’s elevated positioning and high-impact debut.",
    industry: "Health and Wellness Food",
    Images: [
      "/images/projects/meve/img1.webp",
      "/images/projects/meve/img2.webp",
      "/images/projects/meve/img3.webp",
    ],
  },
  {
    id: 13,
    title: "Shivdutt Das Art Foundation",
    tagline: "Crafting a Foundation for the Arts.",
    heroImg: "/images/projects/sdaf/heroImg.webp",
    coverImg: "/images/projects/sdaf/heroImg.webp",
    logo: "/images/projects/sdaf/logo.png",
    websiteLink: "",
    tags: [
      "Brand Strategy",
      "Website Development",
      "Event Management",
      "Social Media",
      "Identity Design",
      "VIP Outreach",
    ],
    challenge:
      "Launching a new art foundation requires more than a great inaugural event — it demands prestige, a compelling voice, and a community built from day one. The Shivdutt Das Art Foundation needed a brand and strategy that would position it as a cultural institution from its very first showcase, 'Timeless Frames.'",
    approach:
      "Our partnership is both foundational and ongoing. We began by crafting a strong digital home through a beautifully designed website, establishing the foundation’s voice and presence. For the inaugural event, 'Timeless Frames,' we delivered an end-to-end experience — from creating the event identity and managing social media build-up to designing bespoke invitations for a high-profile guest list. We also executed live coverage and designed elegant gift boxes for an unforgettable takeaway. Beyond launch, we continue to manage their digital presence and act as a strategic partner shaping the foundation’s long-term vision in the arts and culture space.",
    industry: "Arts and Culture",
    Images: [
      "/images/projects/sdaf/img1.webp",
      "/images/projects/sdaf/img2.webp",
    ],
  },
  {
    id: 14,
    title: "India Maritime Week",
    tagline: "Corporate design that commands attention.",
    heroImg: "/images/projects/imw/heroImg.webp",
    coverImg: "/images/projects/imw/coverImg.webp",
    logo: "/images/projects/imw/logo.png",
    websiteLink: "",
    tags: ["Brochure Design", "Corporate Collateral"],
    challenge:
      "For major industry events, the corporate brochure serves as both a key reference and a reflection of credibility. The challenge was to transform dense, technical content into a format that was visually engaging, easy to navigate, and worthy of the event’s stature.",
    approach:
      "We translated complexity into clarity through smart structure and refined design. Collaborating closely with event organizers, we crafted a brochure that balanced precision with polish — a modern, high-impact piece of corporate collateral that elevated the prestige of India Maritime Week.",
    industry: "Events / Maritime",
    Images: [
      "/images/projects/imw/img1.webp",
      "/images/projects/imw/img2.webp",
      "/images/projects/imw/img3.webp",
      "/images/projects/imw/img4.webp",
      "/images/projects/imw/img5.webp",
    ],
  },
  {
    id: 15,
    title: "Piramal Nextgen",
    tagline: "Crafting essential corporate tools.",
    heroImg: "",
    coverImg: "",
    logo: "/images/projects/piramal/logo.png",
    websiteLink: "",
    tags: ["Website", "Brochure Design"],
    challenge:
      "For a high-end firm in the architecture and turnkey contracting space, every asset must reflect the quality and precision of its work. Piramal Nextgen needed a website and corporate brochure that would serve as the foundational pillars of its marketing, instantly communicating credibility and expertise.",
    approach:
      "We designed and developed the essential tools for their digital and physical presence — a sophisticated website that showcases their portfolio with clarity and style, and a corporate brochure that acts as a powerful leave-behind for clients and presentations. Together, these assets now serve as the cornerstone of their client-facing communication.",
    industry: "Interior Design, Architecture, and Turnkey Contracting",
    Images: [],
  },
  {
    id: 16,
    title: "VS Corporate",
    tagline: "Giving executives a powerful voice.",
    heroImg: "/images/projects/vsCorporate/heroImg.webp",
    coverImg: "/images/projects/vsCorporate/heroImg.webp",
    logo: "/images/projects/vsCorporate/logo.png",
    websiteLink: "",
    tags: ["Executive Strategy", "Social Media", "Content"],
    challenge:
      "In today’s business world, leadership extends beyond the boardroom. The top executives at Vishwa Samudra needed to establish a clear, consistent, and credible public presence on LinkedIn, but lacked the time and strategy to do so effectively.",
    approach:
      "We serve as the strategic content and management team behind their executive brands. Our work involves crafting authentic narratives, producing thought leadership content, and driving engagement that strengthens credibility and visibility — ensuring each leader’s digital voice reflects their professional stature.",
    industry: "Corporate / Conglomerate",
    Images: [
      "/images/projects/vsCorporate/img1.webp",
      "/images/projects/vsCorporate/img2.webp",
      "/images/projects/vsCorporate/img3.webp",
      "/images/projects/vsCorporate/img4.webp",
      "/images/projects/vsCorporate/img5.webp",
      "/images/projects/vsCorporate/img6.webp",
      "/images/projects/vsCorporate/img7.webp",
      "/images/projects/vsCorporate/img8.webp",
      "/images/projects/vsCorporate/img9.webp",
      "/images/projects/vsCorporate/img10.webp",
      "/images/projects/vsCorporate/img11.webp",
    ],
  },
  {
    id: 17,
    title: "Dalhousie Public School",
    tagline: "Bringing a legacy brand online.",
    heroImg: "",
    coverImg: "",
    logo: "/images/projects/dalhousie/logo.svg",
    websiteLink: "",
    tags: ["Website Design", "Development"],
    challenge:
      "Many legacy institutions have reputations that far exceed their digital presence. Dalhousie Public School needed a modern website that would honor its heritage while appealing to today’s digitally native parents and prospective students.",
    approach:
      "We designed and developed a new digital home that balances tradition with technology. The elegant, intuitive website highlights the school’s values, showcases its campus, and serves as an essential resource for parents, students, and alumni — bringing its legacy to life online.",
    industry: "Education",
    Images: [],
  },
  {
    id: 18,
    title: "Candor Foods",
    tagline: "Food that looks good everywhere.",
    heroImg: "",
    coverImg: "",
    logo: "/images/projects/candor/logo.svg",
    websiteLink: "",
    tags: ["Social Media", "Packaging"],
    challenge:
      "In the competitive food and beverage space, products must look as appealing online as they do on-shelf. Candor Foods needed a cohesive brand identity that translated beautifully across packaging and social media.",
    approach:
      "We unified their visual identity across physical and digital touchpoints. Our team designed clean, eye-catching packaging that stood out in retail spaces, and built a social media presence full of appetizing, on-brand visuals — ensuring the brand looked delicious everywhere it appeared.",
    industry: "Food and Beverage",
    Images: [],
  },
  {
    id: 19,
    title: "The Laundry House",
    tagline: "The strategy behind the expansion.",
    heroImg: "",
    coverImg: "",
    logo: "/images/projects/tlh/logo.svg",
    websiteLink: "",
    tags: ["Franchise Strategy", "Social Media"],
    challenge:
      "Scaling a service brand through franchising requires a strong operational base and consistent communication. The Laundry House needed both — a growth strategy and brand management that could support expansion.",
    approach:
      "We developed TLH’s franchise expansion blueprint, including Service-Level Agreements and operational systems to ensure scalable success. Alongside, we managed their social media presence to strengthen the brand and attract both customers and potential franchise partners.",
    industry: "Consumer Services",
    Images: [],
  },
  {
    id: 20,
    title: "Ellementary",
    tagline: "Consistent, beautiful social content.",
    heroImg: "",
    coverImg: "",
    logo: "/images/projects/ellementary/logo.svg",
    websiteLink: "",
    tags: ["Social Media"],
    challenge:
      "For a design-led brand like Ellementary, social media must feel like a seamless extension of its product aesthetic. They needed a partner capable of maintaining both visual consistency and creative excellence across every post.",
    approach:
      "We became the creative engine behind Ellementary’s social media presence — crafting visually cohesive, high-quality content that reflects their design sensibility, engages audiences, and reinforces their leadership in the home and decor category.",
    industry: "Home & Decor / Retail",
    Images: [],
  },
  {
    id: 21,
    title: "Kuwait Airlines",
    tagline: "Agile design support for a global carrier.",
    heroImg: "",
    coverImg: "",
    logo: "/images/projects/kuwait/logo.svg",
    websiteLink: "",
    tags: ["Design", "Social Media Creatives"],
    challenge:
      "A global airline operates at a relentless pace, constantly needing high-quality creative assets for campaigns, promotions, and regional communication. Kuwait Airlines needed a reliable, agile design partner to support their fast-moving operations.",
    approach:
      "We provided ongoing design and creative support, functioning as an extension of their internal marketing team. Our work ensured timely delivery of visually polished, brand-aligned assets across social and digital platforms — helping the airline maintain global consistency with local agility.",
    industry: "Airlines and Aviation",
    Images: [],
  },

];
